//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// fm2024.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FM2024_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_START                134
#define IDD_DIALOG_MAKER                136
#define IDD_DIALOG_SEL                  138
#define IDD_DIALOG_SEARCH               140
#define IDD_FM2024AI_DIALOG             141
#define IDC_EDIT_CORNERS                1000
#define IDC_EDIT_CROSSING               1001
#define IDC_EDIT_DRIBBLING              1002
#define IDC_EDIT_FINISHING              1003
#define IDC_SCROLLBAR_PLAYER            1004
#define IDC_EDIT_NAME                   1005
#define IDC_EDIT_BIRTH                  1006
#define IDC_EDIT_AGE                    1007
#define IDC_EDIT_HEIGHT                 1008
#define IDC_EDIT_WEIGHT                 1009
#define IDC_EDIT_FIRST_TOUCH            1010
#define IDC_EDIT_FREE_KICK              1011
#define IDC_EDIT_HEADING                1012
#define IDC_EDIT_LONG_SHOT              1013
#define IDC_EDIT_LONG_THROW             1014
#define IDC_EDIT_MARKING                1015
#define IDC_EDIT_PASSING                1016
#define IDC_EDIT_PENALTY_TAKING         1017
#define IDC_EDIT_TACKLING               1018
#define IDC_EDIT_TECHNIQUE              1019
#define IDC_EDIT_AGGRESSION             1020
#define IDC_EDIT_ANTICIPATION           1021
#define IDC_EDIT_BRAVERY                1022
#define IDC_EDIT_COMPOSURE              1023
#define IDC_EDIT_CONCENTRATION          1024
#define IDC_EDIT_VISION                 1025
#define IDC_EDIT_DECISION               1026
#define IDC_EDIT_DETERMINATION          1027
#define IDC_EDIT_FLAIR                  1028
#define IDC_EDIT_LEADERSHIP             1029
#define IDC_EDIT_OFF_THE_BALL           1030
#define IDC_EDIT_POSITION_STAT          1031
#define IDC_EDIT_TEAMWORK               1032
#define IDC_EDIT_WORK_RATE              1033
#define IDC_EDIT_ACCELERATION           1034
#define IDC_EDIT_AGILITY                1035
#define IDC_EDIT_BALANCE                1036
#define IDC_EDIT_JUMPING_REACH          1037
#define IDC_EDIT_NATURAL_FITNESS        1038
#define IDC_EDIT_PACE                   1039
#define IDC_EDIT_STAMINA                1040
#define IDC_EDIT_STRENGTH               1041
#define IDC_EDIT_STABILITY              1042
#define IDC_EDIT_FOUL                   1043
#define IDC_EDIT_CP                     1044
#define IDC_EDIT_INJURY                 1045
#define IDC_EDIT_DIVERSITY              1046
#define IDC_EDIT_AERIAL_REACH           1047
#define IDC_EDIT_COA                    1048
#define IDC_EDIT_COMMUNICATION          1049
#define IDC_EDIT_ECCENTRICITY           1050
#define IDC_EDIT_HANDLING               1051
#define IDC_EDIT_KICKING                1052
#define IDC_EDIT_ONE_ON_ONES            1053
#define IDC_EDIT_REFLEXES               1054
#define IDC_EDIT_RUSHING_OUT            1055
#define IDC_EDIT_PUNCHING               1056
#define IDC_EDIT_THROWING               1057
#define IDC_EDIT_ADAPTATION             1058
#define IDC_EDIT_AMBITION               1059
#define IDC_EDIT_ARGUE                  1060
#define IDC_EDIT_LOYAL                  1061
#define IDC_EDIT_RESISTANT_OF_STRESS    1062
#define IDC_EDIT_PROFESSIONAL           1063
#define IDC_EDIT_SPORTSMANSHIP          1064
#define IDC_EDIT_EMOTIONAL_CONTROL      1065
#define IDC_EDIT_POSITION               1066
#define IDC_BUTTON1                     1069
#define IDC_BUTTON_NEXT                 1069
#define IDC_BUTTON_START                1069
#define IDC_BUTTON_PREV                 1070
#define IDC_BUTTON_YOO                  1070
#define IDC_FACE                        1071
#define IDC_BUTTON2                     1073
#define IDC_BUTTON_MAKER                1073
#define IDC_BUTTON_AI                   1073
#define IDC_BUTTON_FIND                 1073
#define IDC_COMBO_STAT2                 1078
#define IDC_BUTTON_STRIKER              1086
#define IDC_EDIT_ALL                    1087
#define IDC_EDIT_COUNT                  1088
#define IDC_BUTTON_WINGER               1089
#define IDC_COMBO_STAT1                 1089
#define IDC_COMBO_STAT3                 1090
#define IDC_BUTTON_ATKMID               1091
#define IDC_BUTTON_CENTMID              1092
#define IDC_BUTTON_DEFMID               1093
#define IDC_BUTTON_LEFTFULL             1094
#define IDC_EDIT_STAT1_MIN              1094
#define IDC_BUTTON_RIGHTFULL            1095
#define IDC_EDIT_HEIGHT_MIN             1095
#define IDC_BUTTON_DEF                  1096
#define IDC_CHECK_STAT1                 1096
#define IDC_BUTTON_GOALKEEP             1097
#define IDC_CHECK_STAT2                 1097
#define IDC_BUTTON_ALL                  1098
#define IDC_CHECK_STAT3                 1098
#define IDC_CHECK_HEIGHT                1099
#define IDC_CHECK_WEIGHT                1100
#define IDC_CHECK_AGE                   1101
#define IDC_EDIT_WEIGHT_MIN             1102
#define IDC_EDIT_STAT1_MAX              1103
#define IDC_EDIT_STAT2_MAX              1104
#define IDC_EDIT_STAT2_MIN              1105
#define IDC_EDIT_STAT3_MIN              1106
#define IDC_EDIT_STAT3_MAX              1107
#define IDC_EDIT_HEIGHT_MAX             1108
#define IDC_EDIT_WEIGHT_MAX             1109
#define IDC_EDIT_AGE_MIN                1110
#define IDC_EDIT_AGE_MAX                1111
#define IDC_CHECK_LEFTFOOT              1112
#define IDC_CHECK_RIGHTFOOT             1113
#define IDC_EDIT_LEFTFOOT_MIN           1114
#define IDC_EDIT_RIGHTFOOT_MIN          1115
#define IDC_EDIT_LEFTFOOT_MAX           1116
#define IDC_EDIT_RIGHTFOOT_MAX          1117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
